version: "2.2"

services:
  db:
    restart: always
    container_name: mysql_db
    build:
      context: .
      dockerfile: Dockerfile_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    healthcheck:
      test: ["CMD", "/bin/nc", "-z", "-v", "localhost", "3306"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./data/db:/var/lib/mysql

  covid_reports:
    restart: on-failure
    build: .
    volumes:
      - .:/backend
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
