# Generated by Django 4.0.3 on 2022-04-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_covidregister_aged_65_older_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidregister',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='covidregister',
            name='new_deaths_per_million',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='covidregister',
            name='new_vaccinations_smoothed_per_hundred',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='covidregister',
            name='tests_units',
            field=models.CharField(max_length=255),
        ),
    ]
