# Generated by Django 4.0.3 on 2022-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_covidregister_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidregister',
            name='new_vaccinations_smoothed_per_hundred',
        ),
    ]
