# Generated by Django 4.0.3 on 2022-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_location_continent_alter_location_iso_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='continent',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
