# Generated by Django 4.0.3 on 2022-04-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_location_continent_alter_location_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidregister',
            name='location',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='reports.location'),
        ),
    ]
